syntax = "proto3";

package partyaffairs.api.public;
option go_package = "kratos-layout/api/public;public";
option java_multiple_files = true;
option java_package = "partyaffairs.api.public";
option java_outer_classname = "PublicV1";

import "validate/validate.proto";

message ListPublicClassifyRequest {
}

message ListPublicClassifyReply {
  message PublicClassify {
    uint32 id = 1;
    string name = 2;
    uint32 weight = 3;
    uint32 createdAt = 4;
    uint32 updatedAt = 5;
  }

  repeated PublicClassify list = 2;
}

message CreatePublicClassifyRequest {
  string name = 1[(validate.rules).string = {min_len: 1}];
  uint32 weight = 2;
}

message CreatePublicClassifyReply {
  uint32 id = 1;
}

message UpdatePublicClassifyRequest {
  uint32 id = 1[(validate.rules).uint32 = {gt: 0}];
  string name = 2[(validate.rules).string = {min_len: 1}];
  uint32 weight = 3;
}

message UpdatePublicClassifyReply {
}

message DeletePublicClassifyRequest {
  uint32 id = 1[(validate.rules).uint32 = {gte:0}];
}

message DeletePublicClassifyReply {
}

