// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/partyaffairs/task/partyaffairs_task_value.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *GetCurTaskValueRequest) Reset() {
	*x = GetCurTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurTaskValueRequest) ProtoMessage() {}

func (x *GetCurTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurTaskValueRequest.ProtoReflect.Descriptor instead.
func (*GetCurTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type GetCurTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId    uint32 `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId    uint32 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt uint32 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *GetCurTaskValueReply) Reset() {
	*x = GetCurTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurTaskValueReply) ProtoMessage() {}

func (x *GetCurTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurTaskValueReply.ProtoReflect.Descriptor instead.
func (*GetCurTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurTaskValueReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCurTaskValueReply) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetCurTaskValueReply) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCurTaskValueReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetCurTaskValueReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetCurTaskValueReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId uint32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetTaskValueRequest) Reset() {
	*x = GetTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskValueRequest) ProtoMessage() {}

func (x *GetTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskValueRequest.ProtoReflect.Descriptor instead.
func (*GetTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskValueRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId    uint32                  `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId    uint32                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Value     string                  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt uint32                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32                  `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	User      *GetTaskValueReply_User `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetTaskValueReply) Reset() {
	*x = GetTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskValueReply) ProtoMessage() {}

func (x *GetTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskValueReply.ProtoReflect.Descriptor instead.
func (*GetTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskValueReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskValueReply) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskValueReply) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTaskValueReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetTaskValueReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTaskValueReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetTaskValueReply) GetUser() *GetTaskValueReply_User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TaskId   uint32  `protobuf:"varint,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId   *uint32 `protobuf:"varint,4,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	Finish   *bool   `protobuf:"varint,5,opt,name=finish,proto3,oneof" json:"finish,omitempty"`
}

func (x *ListTaskValueRequest) Reset() {
	*x = ListTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskValueRequest) ProtoMessage() {}

func (x *ListTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskValueRequest.ProtoReflect.Descriptor instead.
func (*ListTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{4}
}

func (x *ListTaskValueRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTaskValueRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ListTaskValueRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListTaskValueRequest) GetFinish() bool {
	if x != nil && x.Finish != nil {
		return *x.Finish
	}
	return false
}

type ListTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListTaskValueReply_Value `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListTaskValueReply) Reset() {
	*x = ListTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskValueReply) ProtoMessage() {}

func (x *ListTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskValueReply.ProtoReflect.Descriptor instead.
func (*ListTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{5}
}

func (x *ListTaskValueReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTaskValueReply) GetList() []*ListTaskValueReply_Value {
	if x != nil {
		return x.List
	}
	return nil
}

type ExportTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *ExportTaskValueRequest) Reset() {
	*x = ExportTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskValueRequest) ProtoMessage() {}

func (x *ExportTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskValueRequest.ProtoReflect.Descriptor instead.
func (*ExportTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{6}
}

func (x *ExportTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ExportTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportTaskValueReply) Reset() {
	*x = ExportTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTaskValueReply) ProtoMessage() {}

func (x *ExportTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTaskValueReply.ProtoReflect.Descriptor instead.
func (*ExportTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{7}
}

type CreateTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateTaskValueRequest) Reset() {
	*x = CreateTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskValueRequest) ProtoMessage() {}

func (x *CreateTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskValueRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateTaskValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTaskValueReply) Reset() {
	*x = CreateTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskValueReply) ProtoMessage() {}

func (x *CreateTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskValueReply.ProtoReflect.Descriptor instead.
func (*CreateTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTaskValueReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateTaskValueRequest) Reset() {
	*x = UpdateTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskValueRequest) ProtoMessage() {}

func (x *UpdateTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTaskValueRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTaskValueReply) Reset() {
	*x = UpdateTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskValueReply) ProtoMessage() {}

func (x *UpdateTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskValueReply.ProtoReflect.Descriptor instead.
func (*UpdateTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{11}
}

type DeleteTaskValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTaskValueRequest) Reset() {
	*x = DeleteTaskValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskValueRequest) ProtoMessage() {}

func (x *DeleteTaskValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskValueRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskValueRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTaskValueReply) Reset() {
	*x = DeleteTaskValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTaskValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskValueReply) ProtoMessage() {}

func (x *DeleteTaskValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskValueReply.ProtoReflect.Descriptor instead.
func (*DeleteTaskValueReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{13}
}

type GetTaskValueReply_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName  string  `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	RealName  *string `protobuf:"bytes,3,opt,name=realName,proto3,oneof" json:"realName,omitempty"`
	AvatarUrl *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	Phone     *string `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email     *string `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
}

func (x *GetTaskValueReply_User) Reset() {
	*x = GetTaskValueReply_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskValueReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskValueReply_User) ProtoMessage() {}

func (x *GetTaskValueReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskValueReply_User.ProtoReflect.Descriptor instead.
func (*GetTaskValueReply_User) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTaskValueReply_User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskValueReply_User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetTaskValueReply_User) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *GetTaskValueReply_User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *GetTaskValueReply_User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *GetTaskValueReply_User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type ListTaskValueReply_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId    uint32                         `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UserId    uint32                         `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Value     string                         `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt uint32                         `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt uint32                         `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	User      *ListTaskValueReply_Value_User `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ListTaskValueReply_Value) Reset() {
	*x = ListTaskValueReply_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTaskValueReply_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskValueReply_Value) ProtoMessage() {}

func (x *ListTaskValueReply_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskValueReply_Value.ProtoReflect.Descriptor instead.
func (*ListTaskValueReply_Value) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListTaskValueReply_Value) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListTaskValueReply_Value) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ListTaskValueReply_Value) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTaskValueReply_Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListTaskValueReply_Value) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListTaskValueReply_Value) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListTaskValueReply_Value) GetUser() *ListTaskValueReply_Value_User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListTaskValueReply_Value_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName  string  `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	RealName  *string `protobuf:"bytes,3,opt,name=realName,proto3,oneof" json:"realName,omitempty"`
	AvatarUrl *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	Phone     *string `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email     *string `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
}

func (x *ListTaskValueReply_Value_User) Reset() {
	*x = ListTaskValueReply_Value_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTaskValueReply_Value_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskValueReply_Value_User) ProtoMessage() {}

func (x *ListTaskValueReply_Value_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskValueReply_Value_User.ProtoReflect.Descriptor instead.
func (*ListTaskValueReply_Value_User) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *ListTaskValueReply_Value_User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListTaskValueReply_Value_User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *ListTaskValueReply_Value_User) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *ListTaskValueReply_Value_User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *ListTaskValueReply_Value_User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *ListTaskValueReply_Value_User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

var File_api_partyaffairs_task_partyaffairs_task_value_proto protoreflect.FileDescriptor

var file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDesc = []byte{
	0x0a, 0x33, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69,
	0x72, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66,
	0x61, 0x69, 0x72, 0x73, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61,
	0x69, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66,
	0x61, 0x69, 0x72, 0x73, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x54,
	0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x22, 0xa8, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x57, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xd6, 0x03, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x51, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a,
	0xdb, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xd4, 0x01,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a,
	0x02, 0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x01, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x22, 0xd3, 0x04, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x53, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x3f, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xd1, 0x03, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x58, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x44, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0xdb, 0x01, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55,
	0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x03, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f,
	0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x39, 0x0a, 0x16, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x58, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x58, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02,
	0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x31, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescOnce sync.Once
	file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescData = file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDesc
)

func file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescGZIP() []byte {
	file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescOnce.Do(func() {
		file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescData)
	})
	return file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDescData
}

var file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_partyaffairs_task_partyaffairs_task_value_proto_goTypes = []interface{}{
	(*GetCurTaskValueRequest)(nil),        // 0: partyaffairs.api.partyaffairs.task.v1.GetCurTaskValueRequest
	(*GetCurTaskValueReply)(nil),          // 1: partyaffairs.api.partyaffairs.task.v1.GetCurTaskValueReply
	(*GetTaskValueRequest)(nil),           // 2: partyaffairs.api.partyaffairs.task.v1.GetTaskValueRequest
	(*GetTaskValueReply)(nil),             // 3: partyaffairs.api.partyaffairs.task.v1.GetTaskValueReply
	(*ListTaskValueRequest)(nil),          // 4: partyaffairs.api.partyaffairs.task.v1.ListTaskValueRequest
	(*ListTaskValueReply)(nil),            // 5: partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply
	(*ExportTaskValueRequest)(nil),        // 6: partyaffairs.api.partyaffairs.task.v1.ExportTaskValueRequest
	(*ExportTaskValueReply)(nil),          // 7: partyaffairs.api.partyaffairs.task.v1.ExportTaskValueReply
	(*CreateTaskValueRequest)(nil),        // 8: partyaffairs.api.partyaffairs.task.v1.CreateTaskValueRequest
	(*CreateTaskValueReply)(nil),          // 9: partyaffairs.api.partyaffairs.task.v1.CreateTaskValueReply
	(*UpdateTaskValueRequest)(nil),        // 10: partyaffairs.api.partyaffairs.task.v1.UpdateTaskValueRequest
	(*UpdateTaskValueReply)(nil),          // 11: partyaffairs.api.partyaffairs.task.v1.UpdateTaskValueReply
	(*DeleteTaskValueRequest)(nil),        // 12: partyaffairs.api.partyaffairs.task.v1.DeleteTaskValueRequest
	(*DeleteTaskValueReply)(nil),          // 13: partyaffairs.api.partyaffairs.task.v1.DeleteTaskValueReply
	(*GetTaskValueReply_User)(nil),        // 14: partyaffairs.api.partyaffairs.task.v1.GetTaskValueReply.User
	(*ListTaskValueReply_Value)(nil),      // 15: partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.Value
	(*ListTaskValueReply_Value_User)(nil), // 16: partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.Value.User
}
var file_api_partyaffairs_task_partyaffairs_task_value_proto_depIdxs = []int32{
	14, // 0: partyaffairs.api.partyaffairs.task.v1.GetTaskValueReply.user:type_name -> partyaffairs.api.partyaffairs.task.v1.GetTaskValueReply.User
	15, // 1: partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.list:type_name -> partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.Value
	16, // 2: partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.Value.user:type_name -> partyaffairs.api.partyaffairs.task.v1.ListTaskValueReply.Value.User
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_partyaffairs_task_partyaffairs_task_value_proto_init() }
func file_api_partyaffairs_task_partyaffairs_task_value_proto_init() {
	if File_api_partyaffairs_task_partyaffairs_task_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTaskValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskValueReply_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTaskValueReply_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTaskValueReply_Value_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_partyaffairs_task_partyaffairs_task_value_proto_goTypes,
		DependencyIndexes: file_api_partyaffairs_task_partyaffairs_task_value_proto_depIdxs,
		MessageInfos:      file_api_partyaffairs_task_partyaffairs_task_value_proto_msgTypes,
	}.Build()
	File_api_partyaffairs_task_partyaffairs_task_value_proto = out.File
	file_api_partyaffairs_task_partyaffairs_task_value_proto_rawDesc = nil
	file_api_partyaffairs_task_partyaffairs_task_value_proto_goTypes = nil
	file_api_partyaffairs_task_partyaffairs_task_value_proto_depIdxs = nil
}
