syntax = "proto3";

package partyaffairs.api.interflow;
option go_package = "kratos-layout/api/interflow;interflow";
option java_multiple_files = true;
option java_package = "partyaffairs.api.interflow";
option java_outer_classname = "InterflowV1";

import "google/api/annotations.proto";
import "api/interflow/proto/interflow.proto";

service Interflow{

  rpc ListInterflowHistory (ListInterflowHistoryRequest) returns (ListInterflowHistoryReply) {
    option (google.api.http) = {
      get: "/partyaffairs/api/v1/interflow/history",
    };
  }

  // ListInterflowClassify 获取资讯分组列表
  rpc ListInterflowClassify(ListInterflowClassifyRequest) returns(ListInterflowClassifyReply) {
    option(google.api.http) = {
      get: "/partyaffairs/api/v1/interflow/classifies"
    };
  }

  // CreateInterflowClassify 创建资讯分组
  rpc CreateInterflowClassify(CreateInterflowClassifyRequest) returns(CreateInterflowClassifyReply) {
    option(google.api.http) = {
      post: "/partyaffairs/api/v1/interflow/classify",
      body: "*"
    };
  }

  // UpdateInterflowClassify 更新资讯分组
  rpc UpdateInterflowClassify(UpdateInterflowClassifyRequest) returns(UpdateInterflowClassifyReply) {
    option(google.api.http) = {
      put: "/partyaffairs/api/v1/interflow/classify",
      body: "*"
    };
  }

  // DeleteInterflowClassify 删除资讯分组
  rpc DeleteInterflowClassify(DeleteInterflowClassifyRequest) returns(DeleteInterflowClassifyReply) {
    option(google.api.http) = {
      delete: "/partyaffairs/api/v1/interflow/classify"
    };
  }

  // ListInterflow 获取咨询信息列表
  rpc ListInterflow (ListInterflowRequest) returns (ListInterflowReply) {
    option (google.api.http) = {
      get: "/partyaffairs/api/v1/interflows",
    };
  }

  // CreateInterflow 创建咨询信息
  rpc CreateInterflow (CreateInterflowRequest) returns (CreateInterflowReply) {
    option (google.api.http) = {
      post: "/partyaffairs/api/v1/interflow",
      body: "*"
    };
  }

}