// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/partyaffairs/partyaffairs_notice.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc      string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Unit      string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsTop     bool   `protobuf:"varint,6,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	IsRead    bool   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt uint32 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Notice) Reset() {
	*x = Notice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notice) ProtoMessage() {}

func (x *Notice) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notice.ProtoReflect.Descriptor instead.
func (*Notice) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{0}
}

func (x *Notice) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notice) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Notice) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Notice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notice) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *Notice) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notice) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Notice) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PageNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Title    *string `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	NotRead  *bool   `protobuf:"varint,4,opt,name=not_read,json=notRead,proto3,oneof" json:"not_read,omitempty"`
}

func (x *PageNoticeRequest) Reset() {
	*x = PageNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageNoticeRequest) ProtoMessage() {}

func (x *PageNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageNoticeRequest.ProtoReflect.Descriptor instead.
func (*PageNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{1}
}

func (x *PageNoticeRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageNoticeRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageNoticeRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PageNoticeRequest) GetNotRead() bool {
	if x != nil && x.NotRead != nil {
		return *x.NotRead
	}
	return false
}

type PageNoticeUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NoticeId uint32 `protobuf:"varint,3,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	IsRead   bool   `protobuf:"varint,4,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
}

func (x *PageNoticeUserRequest) Reset() {
	*x = PageNoticeUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageNoticeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageNoticeUserRequest) ProtoMessage() {}

func (x *PageNoticeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageNoticeUserRequest.ProtoReflect.Descriptor instead.
func (*PageNoticeUserRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{2}
}

func (x *PageNoticeUserRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageNoticeUserRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageNoticeUserRequest) GetNoticeId() uint32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *PageNoticeUserRequest) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type PageNoticeUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*PageNoticeUserReply_User `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PageNoticeUserReply) Reset() {
	*x = PageNoticeUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageNoticeUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageNoticeUserReply) ProtoMessage() {}

func (x *PageNoticeUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageNoticeUserReply.ProtoReflect.Descriptor instead.
func (*PageNoticeUserReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{3}
}

func (x *PageNoticeUserReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageNoticeUserReply) GetList() []*PageNoticeUserReply_User {
	if x != nil {
		return x.List
	}
	return nil
}

type PageNoticeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*Notice `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PageNoticeReply) Reset() {
	*x = PageNoticeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageNoticeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageNoticeReply) ProtoMessage() {}

func (x *PageNoticeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageNoticeReply.ProtoReflect.Descriptor instead.
func (*PageNoticeReply) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{4}
}

func (x *PageNoticeReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageNoticeReply) GetList() []*Notice {
	if x != nil {
		return x.List
	}
	return nil
}

type AddNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc        string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Unit        string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Content     string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsSendEmail bool   `protobuf:"varint,5,opt,name=is_send_email,json=isSendEmail,proto3" json:"is_send_email,omitempty"`
	IsTop       *bool  `protobuf:"varint,6,opt,name=is_top,json=isTop,proto3,oneof" json:"is_top,omitempty"`
}

func (x *AddNoticeRequest) Reset() {
	*x = AddNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoticeRequest) ProtoMessage() {}

func (x *AddNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoticeRequest.ProtoReflect.Descriptor instead.
func (*AddNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{5}
}

func (x *AddNoticeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddNoticeRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AddNoticeRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AddNoticeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddNoticeRequest) GetIsSendEmail() bool {
	if x != nil {
		return x.IsSendEmail
	}
	return false
}

func (x *AddNoticeRequest) GetIsTop() bool {
	if x != nil && x.IsTop != nil {
		return *x.IsTop
	}
	return false
}

type GetNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetNoticeRequest) Reset() {
	*x = GetNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoticeRequest) ProtoMessage() {}

func (x *GetNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoticeRequest.ProtoReflect.Descriptor instead.
func (*GetNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{6}
}

func (x *GetNoticeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadNoticeRequest) Reset() {
	*x = ReadNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNoticeRequest) ProtoMessage() {}

func (x *ReadNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNoticeRequest.ProtoReflect.Descriptor instead.
func (*ReadNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{7}
}

func (x *ReadNoticeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc        string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Unit        string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Content     string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsSendEmail bool   `protobuf:"varint,5,opt,name=is_send_email,json=isSendEmail,proto3" json:"is_send_email,omitempty"`
	Id          uint32 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	IsTop       *bool  `protobuf:"varint,7,opt,name=is_top,json=isTop,proto3,oneof" json:"is_top,omitempty"`
}

func (x *UpdateNoticeRequest) Reset() {
	*x = UpdateNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoticeRequest) ProtoMessage() {}

func (x *UpdateNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoticeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNoticeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoticeRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateNoticeRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UpdateNoticeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateNoticeRequest) GetIsSendEmail() bool {
	if x != nil {
		return x.IsSendEmail
	}
	return false
}

func (x *UpdateNoticeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNoticeRequest) GetIsTop() bool {
	if x != nil && x.IsTop != nil {
		return *x.IsTop
	}
	return false
}

type DeleteNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteNoticeRequest) Reset() {
	*x = DeleteNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoticeRequest) ProtoMessage() {}

func (x *DeleteNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoticeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNoticeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageNoticeUserReply_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName  string  `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	RealName  *string `protobuf:"bytes,3,opt,name=realName,proto3,oneof" json:"realName,omitempty"`
	AvatarUrl *string `protobuf:"bytes,4,opt,name=avatarUrl,proto3,oneof" json:"avatarUrl,omitempty"`
	Gender    *string `protobuf:"bytes,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
}

func (x *PageNoticeUserReply_User) Reset() {
	*x = PageNoticeUserReply_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageNoticeUserReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageNoticeUserReply_User) ProtoMessage() {}

func (x *PageNoticeUserReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageNoticeUserReply_User.ProtoReflect.Descriptor instead.
func (*PageNoticeUserReply_User) Descriptor() ([]byte, []int) {
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PageNoticeUserReply_User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PageNoticeUserReply_User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PageNoticeUserReply_User) GetRealName() string {
	if x != nil && x.RealName != nil {
		return *x.RealName
	}
	return ""
}

func (x *PageNoticeUserReply_User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *PageNoticeUserReply_User) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

var File_api_partyaffairs_partyaffairs_notice_proto protoreflect.FileDescriptor

var file_api_partyaffairs_partyaffairs_notice_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69,
	0x72, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73,
	0x5f, 0x74, 0x6f, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x54, 0x6f,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x50, 0x61, 0x67,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x20, 0x00, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1e,
	0x0a, 0x08, 0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x72, 0x65, 0x61, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x20, 0x00, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00,
	0x52, 0x08, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x52,
	0x65, 0x61, 0x64, 0x22, 0xb7, 0x02, 0x0a, 0x13, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x4e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x3a, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x1a, 0xb9, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x61, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55,
	0x72, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x65, 0x0a,
	0x0f, 0x50, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66, 0x61,
	0x69, 0x72, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x72, 0x74, 0x79, 0x61, 0x66, 0x66,
	0x61, 0x69, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0xd9, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x06, 0x69, 0x73, 0x5f,
	0x74, 0x6f, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x69, 0x73, 0x54,
	0x6f, 0x70, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x69, 0x73, 0x5f, 0x74, 0x6f, 0x70,
	0x22, 0x2b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a,
	0x11, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf5, 0x01, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x1b, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x21, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x06,
	0x69, 0x73, 0x5f, 0x74, 0x6f, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05,
	0x69, 0x73, 0x54, 0x6f, 0x70, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x69, 0x73, 0x5f,
	0x74, 0x6f, 0x70, 0x22, 0x2e, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_partyaffairs_partyaffairs_notice_proto_rawDescOnce sync.Once
	file_api_partyaffairs_partyaffairs_notice_proto_rawDescData = file_api_partyaffairs_partyaffairs_notice_proto_rawDesc
)

func file_api_partyaffairs_partyaffairs_notice_proto_rawDescGZIP() []byte {
	file_api_partyaffairs_partyaffairs_notice_proto_rawDescOnce.Do(func() {
		file_api_partyaffairs_partyaffairs_notice_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_partyaffairs_partyaffairs_notice_proto_rawDescData)
	})
	return file_api_partyaffairs_partyaffairs_notice_proto_rawDescData
}

var file_api_partyaffairs_partyaffairs_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_partyaffairs_partyaffairs_notice_proto_goTypes = []interface{}{
	(*Notice)(nil),                   // 0: partyaffairs.api.partyaffairs.v1.Notice
	(*PageNoticeRequest)(nil),        // 1: partyaffairs.api.partyaffairs.v1.PageNoticeRequest
	(*PageNoticeUserRequest)(nil),    // 2: partyaffairs.api.partyaffairs.v1.PageNoticeUserRequest
	(*PageNoticeUserReply)(nil),      // 3: partyaffairs.api.partyaffairs.v1.PageNoticeUserReply
	(*PageNoticeReply)(nil),          // 4: partyaffairs.api.partyaffairs.v1.PageNoticeReply
	(*AddNoticeRequest)(nil),         // 5: partyaffairs.api.partyaffairs.v1.AddNoticeRequest
	(*GetNoticeRequest)(nil),         // 6: partyaffairs.api.partyaffairs.v1.GetNoticeRequest
	(*ReadNoticeRequest)(nil),        // 7: partyaffairs.api.partyaffairs.v1.ReadNoticeRequest
	(*UpdateNoticeRequest)(nil),      // 8: partyaffairs.api.partyaffairs.v1.UpdateNoticeRequest
	(*DeleteNoticeRequest)(nil),      // 9: partyaffairs.api.partyaffairs.v1.DeleteNoticeRequest
	(*PageNoticeUserReply_User)(nil), // 10: partyaffairs.api.partyaffairs.v1.PageNoticeUserReply.User
}
var file_api_partyaffairs_partyaffairs_notice_proto_depIdxs = []int32{
	10, // 0: partyaffairs.api.partyaffairs.v1.PageNoticeUserReply.list:type_name -> partyaffairs.api.partyaffairs.v1.PageNoticeUserReply.User
	0,  // 1: partyaffairs.api.partyaffairs.v1.PageNoticeReply.list:type_name -> partyaffairs.api.partyaffairs.v1.Notice
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_partyaffairs_partyaffairs_notice_proto_init() }
func file_api_partyaffairs_partyaffairs_notice_proto_init() {
	if File_api_partyaffairs_partyaffairs_notice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageNoticeUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageNoticeUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageNoticeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageNoticeUserReply_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_api_partyaffairs_partyaffairs_notice_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_partyaffairs_partyaffairs_notice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_partyaffairs_partyaffairs_notice_proto_goTypes,
		DependencyIndexes: file_api_partyaffairs_partyaffairs_notice_proto_depIdxs,
		MessageInfos:      file_api_partyaffairs_partyaffairs_notice_proto_msgTypes,
	}.Build()
	File_api_partyaffairs_partyaffairs_notice_proto = out.File
	file_api_partyaffairs_partyaffairs_notice_proto_rawDesc = nil
	file_api_partyaffairs_partyaffairs_notice_proto_goTypes = nil
	file_api_partyaffairs_partyaffairs_notice_proto_depIdxs = nil
}
