server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
    formatResponse: true
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
log:
  level: 0 #日志输出等级
  output:
    - stdout # stdout:控制台输出，k8s日志收集
    - file # file:输出到文件
  file: #output存在file时此配置才可生效
    name: ./tmp/runtime/output.log #日志存放地址
    maxSize: 1 #日志文件最大容量,单位m
    maxBackup: 5 #日志文件最多保存个数
    maxAge: 1 #保留就文件的最大天数,单位天
    compress: false #是否进行压缩归档
database:
  system: #数据库实例名称,如有多个数据库可新增
    enable: false #是否启用数据库
    drive: mysql #数据库类型
    dsn: root:root@tcp(127.0.0.1:3306)/operation?charset=utf8mb4&parseTime=True&loc=Local #连接dsn
    maxLifetime: 2h #最大生存时间
    maxOpenConn: 10 #最大连接数量
    maxIdleConn: 10 #最大空闲数量
    logLevel: 1 #日志等级
    slowThreshold: 2s #慢sql阈值
redis:
  catch: #redis实例名称,如有多个redis可新增
    enable: false #是否启用redis
    host: 127.0.0.1:6379 #redis地址
    username:  #连接账号
    password:  #连接密码
#loader: #文件加载器相关
#  passwordCert: cert/password.pub #证书路径
pool: #并非池配置
  size: 100000 #最大协程数量
  expiryDuration: 30s #过期时间
  preAlloc: true #是否预分配
  maxBlockingTasks: 1000 #最大的并发任务
  nonblocking: true #设置为true时maxBlockingTasks讲失效，不限制并发任务
email: # 邮件发送相关配置
  template: #邮件模板
    captcha:  #邮件模板名称
      subject: 验证码发送通知 #邮件模板主题
      path: static/template/email/default.html #邮件模板路径
      from: xxx@qq.com
      type: "text/html" #文本内容格式
  user: 860808187@qq.com #发送者
  host: smtp.qq.com:25 #发送host
  password: ersukmsstobebdef # 发送host密码
captcha:
  login:  #验证码名称
    type: image #验证码类型 目前支持image/email
    length: 6 #验证码长度
    expire: 180s #过期时间
    redis: cache #redis名称
    height: 801 #图片高度,仅image有效
    width: 240 #图片宽度,仅image有效
    skew: 0.7 #验证数字倾斜程度,仅image有效
    dotCount: 80 #干扰像素点数量,仅image有效
  changePassword:  #验证码名称
    type: email #验证码类型
    length: 6 #验证码长度
    expire: 180s #过期时间
    redis: cache #redis名称
    template: captcha #邮箱模板名称,仅email有效
#jwt:
#  enable: true #是否开启jwt
#  secret: "hello world" #密钥
#  expire: 2h #过期时间
#  whitelist: #忽略token校验以及鉴权的白名单
#    GET:/helloworld/fangweiye: false #仅 http可用 方法名:path
#    v1:Greeter/SayHello: true #http和grpc通用 包名.服务名.函数名 具体可在pb里面查看
#以下存放业务配置
business:
  openWeb: false
