// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: api/interflow/proto/interflow_service.proto

package interflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Interflow_ListInterflowPerson_FullMethodName   = "/partyaffairs.api.interflow.Interflow/ListInterflowPerson"
	Interflow_CreateInterflowPerson_FullMethodName = "/partyaffairs.api.interflow.Interflow/CreateInterflowPerson"
	Interflow_DeleteInterflowPerson_FullMethodName = "/partyaffairs.api.interflow.Interflow/DeleteInterflowPerson"
	Interflow_ListInterflow_FullMethodName         = "/partyaffairs.api.interflow.Interflow/ListInterflow"
	Interflow_CreateInterflow_FullMethodName       = "/partyaffairs.api.interflow.Interflow/CreateInterflow"
)

// InterflowClient is the client API for Interflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterflowClient interface {
	// ListInterflowPerson 获取资料分组列表
	ListInterflowPerson(ctx context.Context, in *ListInterflowPersonRequest, opts ...grpc.CallOption) (*ListInterflowPersonReply, error)
	// CreateInterflowPerson 创建资料分组
	CreateInterflowPerson(ctx context.Context, in *CreateInterflowPersonRequest, opts ...grpc.CallOption) (*CreateInterflowPersonReply, error)
	// DeleteInterflowPerson 删除资料分组
	DeleteInterflowPerson(ctx context.Context, in *DeleteInterflowPersonRequest, opts ...grpc.CallOption) (*DeleteInterflowPersonReply, error)
	// ListInterflow 获取咨询信息列表
	ListInterflow(ctx context.Context, in *ListInterflowRequest, opts ...grpc.CallOption) (*ListInterflowReply, error)
	// CreateInterflow 创建咨询信息
	CreateInterflow(ctx context.Context, in *CreateInterflowRequest, opts ...grpc.CallOption) (*CreateInterflowReply, error)
}

type interflowClient struct {
	cc grpc.ClientConnInterface
}

func NewInterflowClient(cc grpc.ClientConnInterface) InterflowClient {
	return &interflowClient{cc}
}

func (c *interflowClient) ListInterflowPerson(ctx context.Context, in *ListInterflowPersonRequest, opts ...grpc.CallOption) (*ListInterflowPersonReply, error) {
	out := new(ListInterflowPersonReply)
	err := c.cc.Invoke(ctx, Interflow_ListInterflowPerson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interflowClient) CreateInterflowPerson(ctx context.Context, in *CreateInterflowPersonRequest, opts ...grpc.CallOption) (*CreateInterflowPersonReply, error) {
	out := new(CreateInterflowPersonReply)
	err := c.cc.Invoke(ctx, Interflow_CreateInterflowPerson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interflowClient) DeleteInterflowPerson(ctx context.Context, in *DeleteInterflowPersonRequest, opts ...grpc.CallOption) (*DeleteInterflowPersonReply, error) {
	out := new(DeleteInterflowPersonReply)
	err := c.cc.Invoke(ctx, Interflow_DeleteInterflowPerson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interflowClient) ListInterflow(ctx context.Context, in *ListInterflowRequest, opts ...grpc.CallOption) (*ListInterflowReply, error) {
	out := new(ListInterflowReply)
	err := c.cc.Invoke(ctx, Interflow_ListInterflow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interflowClient) CreateInterflow(ctx context.Context, in *CreateInterflowRequest, opts ...grpc.CallOption) (*CreateInterflowReply, error) {
	out := new(CreateInterflowReply)
	err := c.cc.Invoke(ctx, Interflow_CreateInterflow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterflowServer is the server API for Interflow service.
// All implementations must embed UnimplementedInterflowServer
// for forward compatibility
type InterflowServer interface {
	// ListInterflowPerson 获取资料分组列表
	ListInterflowPerson(context.Context, *ListInterflowPersonRequest) (*ListInterflowPersonReply, error)
	// CreateInterflowPerson 创建资料分组
	CreateInterflowPerson(context.Context, *CreateInterflowPersonRequest) (*CreateInterflowPersonReply, error)
	// DeleteInterflowPerson 删除资料分组
	DeleteInterflowPerson(context.Context, *DeleteInterflowPersonRequest) (*DeleteInterflowPersonReply, error)
	// ListInterflow 获取咨询信息列表
	ListInterflow(context.Context, *ListInterflowRequest) (*ListInterflowReply, error)
	// CreateInterflow 创建咨询信息
	CreateInterflow(context.Context, *CreateInterflowRequest) (*CreateInterflowReply, error)
	mustEmbedUnimplementedInterflowServer()
}

// UnimplementedInterflowServer must be embedded to have forward compatible implementations.
type UnimplementedInterflowServer struct {
}

func (UnimplementedInterflowServer) ListInterflowPerson(context.Context, *ListInterflowPersonRequest) (*ListInterflowPersonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterflowPerson not implemented")
}
func (UnimplementedInterflowServer) CreateInterflowPerson(context.Context, *CreateInterflowPersonRequest) (*CreateInterflowPersonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterflowPerson not implemented")
}
func (UnimplementedInterflowServer) DeleteInterflowPerson(context.Context, *DeleteInterflowPersonRequest) (*DeleteInterflowPersonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInterflowPerson not implemented")
}
func (UnimplementedInterflowServer) ListInterflow(context.Context, *ListInterflowRequest) (*ListInterflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterflow not implemented")
}
func (UnimplementedInterflowServer) CreateInterflow(context.Context, *CreateInterflowRequest) (*CreateInterflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterflow not implemented")
}
func (UnimplementedInterflowServer) mustEmbedUnimplementedInterflowServer() {}

// UnsafeInterflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterflowServer will
// result in compilation errors.
type UnsafeInterflowServer interface {
	mustEmbedUnimplementedInterflowServer()
}

func RegisterInterflowServer(s grpc.ServiceRegistrar, srv InterflowServer) {
	s.RegisterService(&Interflow_ServiceDesc, srv)
}

func _Interflow_ListInterflowPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterflowPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterflowServer).ListInterflowPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interflow_ListInterflowPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterflowServer).ListInterflowPerson(ctx, req.(*ListInterflowPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interflow_CreateInterflowPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInterflowPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterflowServer).CreateInterflowPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interflow_CreateInterflowPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterflowServer).CreateInterflowPerson(ctx, req.(*CreateInterflowPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interflow_DeleteInterflowPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInterflowPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterflowServer).DeleteInterflowPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interflow_DeleteInterflowPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterflowServer).DeleteInterflowPerson(ctx, req.(*DeleteInterflowPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interflow_ListInterflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterflowServer).ListInterflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interflow_ListInterflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterflowServer).ListInterflow(ctx, req.(*ListInterflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interflow_CreateInterflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInterflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterflowServer).CreateInterflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interflow_CreateInterflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterflowServer).CreateInterflow(ctx, req.(*CreateInterflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Interflow_ServiceDesc is the grpc.ServiceDesc for Interflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partyaffairs.api.interflow.Interflow",
	HandlerType: (*InterflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInterflowPerson",
			Handler:    _Interflow_ListInterflowPerson_Handler,
		},
		{
			MethodName: "CreateInterflowPerson",
			Handler:    _Interflow_CreateInterflowPerson_Handler,
		},
		{
			MethodName: "DeleteInterflowPerson",
			Handler:    _Interflow_DeleteInterflowPerson_Handler,
		},
		{
			MethodName: "ListInterflow",
			Handler:    _Interflow_ListInterflow_Handler,
		},
		{
			MethodName: "CreateInterflow",
			Handler:    _Interflow_CreateInterflow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/interflow/proto/interflow_service.proto",
}
